// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.donald.proto;

public final class Chat {
  private Chat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nchat.proto\032\031google/protobuf/any.proto\032" +
      "\013enums.protoB\022\n\020com.donald.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.donald.proto.Enums.getDescriptor(),
        });
    com.google.protobuf.AnyProto.getDescriptor();
    com.donald.proto.Enums.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
